language: node_js
node_js:
- '0.10'
before_install:
- npm install coffee-script
before_script:
- ./node_modules/.bin/cake archive
script:
- ./node_modules/.bin/cake test
deploy:
  provider: releases
  api_key:
    secure: budt3SN4x0yJqfnFSyoR30SmMw1cGmTm8LYvKvewhb32nI/LxPa55HZSgzeCmK1GFDTdqzTpQXVl3mGart2t72bdCwmfNTmQJTo+d3efFlHTv6l1fXDbFRBjtFuWa44XcuWCBBU6kP4ox3cIrfZPU3u/1tWOWOhGX54BljXe7STdnLg7ZlT3eEcXQKmwBXuaWrJzecsG9RpMclxcYAk+mnzB+/4A+25t8DmptgCb3LkMWLDctLIKDZsvQRCkwITt66QTpAbttryff/GbKYQW1AfwbsQ5oeYX2tbBr1xD4Y0c9GyEdWQaHIubPf1CYs0RxCnc2ca0TTRfLgdcdneDwUu2J8C0kLDsY+O2lbgW7peLNYb9CEpRM0EQpKG9o2ea+FUB3hAZpEvBBPWrOLGUir1WrqfcgE2DDOA3Xl8MWRSdmyQ/drHOE2grPCUy89gE1ta83aPO0AAYy3PbMlHh9Ujwdf995SOyXz6xDpJaJ/OV61VLtZWGC5SwZ1U8bHbIu++ZmpKz0WSzDFmgQrOXsv2Cfhzr9fps7k2aDqgXUyYdPLHFpbx16uUbhbGb2fpAorCo7Wxrqt1SjJUthZyzTrsjYqH3E3e90Sxgbg/BrWpmDq4G9ktDwmo593XT16Hyysb0l0MWFxgpYyR3knlfApTZEv7KXILxHsOLMuuvgp4=
  file: build/WADLImporter.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: luckymarmot/Paw-WADLImporter
